### ISSUE TITLE
Using promise to setSelf in atom's effect

### ISSUE THREAD

**Issue by xotahal** [facebookexperimental/Recoil#1107] opened 2021-07-08 13:03 UTC
Hey folks! First of all thanks for the Recoil. Appreciate it! 🙏

I am having this weird behaviour with using promise in atom's effect. Based on this part of [doc](https://recoiljs.org/docs/guides/atom-effects#state-synchronization-example). Let me talk you through this codesandbox - https://codesandbox.io/s/set-self-with-promise-b0z6l?file=/src/App.js

#### How to reproduce
- press execute pre-fetch
- it Suspenses with `Value loading...` for 500ms and then it displays number 8 (because promise on line 58 got resolved)
- after 1500ms there is another promise that gets resolved and should update the value to number 10 (on line 31) - **but it doesn't** (you can see this in console)
- then you can press 2. button to update value, you will see console logs with number incrementing but values stays the same

#### How to reproduce
- comment out the `setSelf` on line 58 (get rid of init promise)
- press prefetch
- you won't see `Value loading...` because it doesn't suspense, you will see 1 instead (default on line 77) for 1500ms then you will see number 10 (timer on line 31)
- when you press 2. button it will updates the value correctly, but you can see this console log twice - `console.log("dataAtom setSelf onchange#", instance, value);`
- **seems that the effect was registered twice**

Please let me know if I can help with this. Or if I am doing anything wrong.

**Comment by drarmstr** [comment] 2021-07-12 17:28
1 doesn't seem to be related to using a Promise, and it seems to work if you show the value of the atom directly, so maybe related to selector subscription (cc @csantos42)

**Comment by drarmstr** [comment] 2021-07-27 23:25
UPDATE (@xotahal ):

1) A fix for this issue is landing shortly, just pending a unit test

2) Seems like this behavior is actually expected.  The documented [pre-fetch example](https://recoiljs.org/docs/guides/asynchronous-data-queries/#pre-fetching) uses a `selectorFamily()` to model an async query.  In your example you used an `atomFamily()` with an effect.  Since the pre-fetch is operating on a `Snapshot`, the pre-fetch request is causing the atom in the family to be used for the first-time and initialized.  But, that's only for that state snapshot and doesn't affect the actual live state in the `<RecoilRoot>`.  When the atom in the family is accessed again when rendering from the actual `<RecoilRoot>` context, then it is essentially seen from that state store for the first time and initializing the actual atom in the live store, that is why you are seeing the effect run twice.  

If you want to do this kind of pre-fetching with atom families, it may be a better option to use `useRecoilTransaction_UNSTABLE()` instead of `useRecoilCallback()`.  Something for us to test with the upcoming release.

**Comment by drarmstr** [comment] 2021-07-29 03:48
Issue 1 fixed with #1135

**Comment by drarmstr** [comment] 2021-07-29 21:52
Tested and confirmed that using `useRecoilTransaction_UNSTABLE()` with Recoil 0.4.0 solves the duplicate effects issue (https://codesandbox.io/s/set-self-with-promise-forked-d66bl?file=/src/App.js).  Though, note that transactions do not quite yet support selectors.

**Closed by drarmstr** 2021-07-29 21:52 UTC
Labels: bug
