### ISSUE TITLE
Feature Request: Access get() function inside atom effects

### ISSUE THREAD

**Issue by JohannesKlauss** [facebookexperimental/Recoil#850] opened 2021-01-26 14:01 UTC
I don't know if this is on the roadmap already, but after integrating atom effects in my app, I realized it would be a massive improvement if one could read state inside the atom effect. I imagine something like this:

```ts
export const undoRedoEffect = <T>(key: string): AtomEffect<T> => ({ setSelf, onSet, get }) => {
  if (get(someOtherAtom) === true) {
    onSet((newValue, oldValue) => {
      history.push({
        label: `${key}: ${JSON.stringify(oldValue)} -> ${JSON.stringify(newValue)}`,
        undo: () => {
          setSelf(oldValue);
        },
      });
    });
  }
};
```

This way one could execute effects conditionally. I am only talking about reading state, not setting any other (to keep it pure).
I think this would be a very powerful feature.

**Comment by justintoman** [comment] 2021-02-01 23:22
This is kind of beside the point, but I would assume you'd only get access to snapshots in there, not a full `get`. I think `get` would imply subscription as well as synchronous execution.

I've wanted this ability as well! 👍

**Comment by JohannesKlauss** [comment] 2021-02-02 12:43
Sure, snapshots are fine as well.

**Comment by drarmstr** [comment] 2021-02-03 00:49
Duplicate of #707 for `getSnapshot()` callback in effect.  So far we tried to avoid this complication as it may not be clear to users the implications of subscriptions, relative ordering, etc.

**Closed by drarmstr** 2021-02-03 00:49 UTC
Labels: duplicate
