### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by RichardLindhout** [facebookexperimental/Recoil#6] opened 2020-05-14 17:27 UTC
Very promising library! 

Any plans for adding Typescript support?

**Comment by davidmccabe** [comment] 2020-05-14 17:28
@csantos42  is currently working on this. Thanks for your interest!

**Comment by csantos42** [comment] 2020-05-14 20:51
For anyone curious I'm working on this at https://github.com/csantos42/DefinitelyTyped/blob/recoil-types/types/recoil/index.d.ts -- PR to DefinitelyTyped coming soon!

**Comment by divyanshu-rawat** [comment] 2020-05-14 21:32
@csantos42, @davidmccabe do you need any help in adding the TS types to components? :)

**Comment by ayush987goyal** [comment] 2020-05-15 04:23
@csantos42 Instead of adding types to DefinitelyTyped repo, how about shipping them alongside Recoil and adding them to this repo itself?

**Comment by guilhermedeandrade** [comment] 2020-05-15 06:53
> @csantos42 Instead of adding types to DefinitelyTyped repo, how about shipping them alongside Recoil and adding them to this repo itself?

This would be a better approach IMO

**Comment by csantos42** [comment] 2020-05-15 07:08
Thanks for offering help @divyanshu-rawat ! No help needed with this at this time, but if anything changes I'll let you know :)

**Comment by csantos42** [comment] 2020-05-15 07:19
@ayush987goyal @guilhermedeandrade I agree having the type definitions in the repo itself would be ideal. The idea for now is that we will add the types to DefinitelyTyped so that we can publish updates to Recoil separately from TS updates until we're ready to commit to keeping TS in sync with every update (the core is written in Flow, so we're going to have to maintain TypeScript types separately).

With that said we'll do our best to keep the TS types up-to-date and in-sync with all updates.

**Comment by guilhermedeandrade** [comment] 2020-05-15 07:20
> @ayush987goyal @guilhermedeandrade I agree having the type definitions in the repo itself would be ideal. The idea for now is that we will add the types to DefinitelyTyped so that we can publish updates to Recoil separately from TS updates until we're ready to commit to keeping TS in sync with every update (the core is written in Flow, so we're going to have to maintain TypeScript types separately).
> 
> With that said we'll do our best to keep the TS types up-to-date and in-sync with all updates.

Thank you 🙏

**Comment by csantos42** [comment] 2020-05-15 18:13
PR is live! https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44756

**Comment by claudiopro** [comment] 2020-05-15 22:58
@mbohgard Flow is the JS typechecker in use for FB's www codebase and is not going away anytime soon. The code in this repo is synced with www so it must use Flow types.

**Comment by taneba** [comment] 2020-05-16 23:06
With TypeScript, it'd be great to be able to type argument of the hook like useRecoilState as a union type of the atoms and selectors. Given that each atom and selector should be globally unique, I think without type helper like this can be a mess at scale.

**Comment by RichardLindhout** [comment] 2020-05-17 12:01
Yes I think they do that, we created a global state library which is Influenced by Recoil api and type safe you only have to define the type globally and if you use the hook it automatically 'gets' the type. https://www.npmjs.com/package/react-ridge-state. I think Recoil will work the same.

**Comment by sallar** [comment] 2020-05-18 09:10
I personally think not supporting TS out of the box is a bit of deal breaker for many many projects. Not many people use Flow and I understand that this is an internal FB decision, but maybe this is a bigger conversation on why is FB still insisting on Flow instead of TS.

**Comment by joesonw** [comment] 2020-05-19 01:43
@sallar I assume politics might be one big reason. Future licensing can also be a threat, Facebook knows best about this.

**Comment by donkeedong** [comment] 2020-05-19 15:53
> PR is live! [DefinitelyTyped/DefinitelyTyped#44756](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44756)
> 
> Now we wait for review/merge

Man they take forever to approve over there, don't they?

**Comment by davidmccabe** [comment] 2020-05-20 02:28
@csantos42  Your pullreq has been hanging out there for a couple days. What would be the tradeoffs of just having the TS bindings in our own repo instead?

**Comment by atanasster** [comment] 2020-05-20 02:51
@davidmccabe - I believe a mentioned tradeoff above is that the ts definitions would need to be maintained alongside every release of recoil itself. 
For me, its a serious downer that even if the ts definitions are published, they will be second priority and can get out of sync at any time. Maybe other users will have a different opinion, just my 0.02. Flow...

**Comment by mbohgard** [comment] 2020-05-20 07:27
The general recommendation I believe is that if your project is written in TypeScript, then include it in the lib. If not, typings should be in the DefinitelyTyped repo.

**Comment by sallar** [comment] 2020-05-20 07:48
I wonder how hard would it be if we just fork this project...

**Comment by ralexand56** [comment] 2020-05-20 15:37
Really starting to dislike the not invented here policy facebook has been employing regarding typescript.

**Comment by dustinsoftware** [comment] 2020-05-20 15:47
This issue is getting a bit off topic;

Keeping TS types in Definitely Typed seems like the right move for the project in its current state if it needs to keep using Flow.

**Comment by andreastoermer** [comment] 2020-05-20 15:57
@csantos42 They wait for your reaction to some points. If you're not reacting, the recoil types will not be useable.

**Comment by csantos42** [comment] 2020-05-20 16:15
Hi all, thanks to everyone that provided feedback on the types— I’ll be addressing them all today so that we can get that PR merged. I’ll keep you posted

**Comment by andreastoermer** [comment] 2020-05-23 08:30
@csantos42 They again need some response from you. If you will not deliver them, they will not merge the PR.

**Comment by ralexand56** [comment] 2020-05-23 15:35
Can we also get some examples of typing things like atoms.

**Comment by ralexand56** [comment] 2020-05-25 02:22
> Hi all, thanks to everyone that provided feedback on the types— I’ll be addressing them all today so that we can get that PR merged. I’ll keep you posted

Any updates on this?

**Comment by isolationzhl** [comment] 2020-05-28 03:27
Whether there is progress?

**Comment by dvakatsiienko** [comment] 2020-05-28 09:20
We tried recoil to persist tables pagination and filtering states between page transitions along with binding those states to Apollo GraphQL querying — looks and feels awesome!
It's great to get rid of Redux boilerplate, although not having loggind support is not so great, overall simplification is awesome.

So watching to Recoil with a great interest and expectation

**Comment by drarmstr** [comment] 2020-05-28 16:34
@dvakatsiienko - Could you clarify what you are looking for with "loggind support"?

**Comment by gobigfoot** [comment] 2020-05-28 16:45
> @dvakatsiienko - Could you clarify what you are looking for with "loggind support"?

Redux supports middleware that allows you to inject custom code that can log the actions that are being called. Supporting middleware would be a nice addition, but I could see complication when people want to start adding Thunks and Sagas.

**Comment by drarmstr** [comment] 2020-05-28 17:01
This seems off-topic from TypeScript support.  You can use the [transaction observer hook](https://recoiljs.org/docs/guides/persistence) to observe all state changes for persistence, debugging, logging, etc.  But, we should move that discussion to another issue.

**Comment by dvakatsiienko** [comment] 2020-05-28 17:22
> @dvakatsiienko - Could you clarify what you are looking for with "loggind support"?

Recoil has an outstanding mechanism model when you have one or two atoms, but it will indeed become complex with a lot of atoms added thats why some kind of devtool or a «logger» like «redux logger» would be nice to have here, that's what I meant.

**Comment by ralexand56** [comment] 2020-05-28 18:10
> This seems off-topic from TypeScript support. You can use the [transaction observer hook](https://recoiljs.org/docs/guides/persistence) to observe all state changes for persistence, debugging, logging, etc. But, we should move that discussion to another issue.

Is it possible to get a status update?

**Comment by csantos42** [comment] 2020-05-28 18:18
hi all sorry for the delay, we're still going back and forth on a few things in the DefinitelyTyped PR, but hopefully they'll be resolved soon. Will post here as soon as I have an update @ralexand56

**Comment by ralexand56** [comment] 2020-05-28 18:39
> hi all sorry for the delay, we're still going back and forth on a few things in the DefinitelyTyped PR, but hopefully they'll be resolved soon. Will post here as soon as I have an update @ralexand56

Thanks for the update! When thinks settle down, can you also share examples of how you're setting types for atoms etc.

**Comment by atomAltera** [comment] 2020-05-29 05:06
Hi all. Why not to put type definition inside this package?

**Comment by hauptrolle** [comment] 2020-05-29 09:02
> @ayush987goyal @guilhermedeandrade I agree having the type definitions in the repo itself would be ideal. The idea for now is that we will add the types to DefinitelyTyped so that we can publish updates to Recoil separately from TS updates until we're ready to commit to keeping TS in sync with every update (the core is written in Flow, so we're going to have to maintain TypeScript types separately).
> 
> With that said we'll do our best to keep the TS types up-to-date and in-sync with all updates.

Did you read the issue? It is already answered :)  @atomAltera

**Comment by csantos42** [comment] 2020-05-29 19:09
TypeScript types [have been merged](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44756) to DefinitelyTyped! In a few hours, you should be able to install them by running:

```bash
yarn add --dev @types/recoil
```
or
```bash
npm install --save-dev @types/recoil
```

I'll work on a guide in the documentation to give an overview of how to use Recoil w/ TypeScript.

Thanks to everyone that contributed/reviewed/commented on this effort! For any subsequent TypeScript updates, please open an issue in the DefinitelyTyped repo. 

I'll close this task once I've confirmed the types are on NPM.

**Comment by jaredpalmer** [comment] 2020-05-29 19:15
@csantos42 here are changes required for recently merged `atomFamily` and `selectorFamily` I've been using on my fork:

```tsx
export type AtomFamilyOptions<T, Parameter> = Readonly<{
  key: NodeKey;
  default:
    | RecoilValue<T>
    | Promise<T>
    | T
    | ((params: Parameter) => T | RecoilValue<T> | Promise<T>);
  // persistence_UNSTABLE?: PersistenceSettings<T>,
  dangerouslyAllowMutability?: boolean;
}>;

export function atomFamily<T, Parameter>(
  options: AtomFamilyOptions<T, Parameter>,
): (params: Parameter) => RecoilState<T>;

```

```tsx
export interface ReadOnlySelectorFamilyOptions<T, Parameter> {
  key: string;
  get: (
    params: Parameter,
  ) => (opts: {get: GetRecoilValue}) => Promise<T> | RecoilValue<T> | T;

  // cacheImplementation_UNSTABLE?: CacheImplementation<Loadable<T>>,
  dangerouslyAllowMutability?: boolean;
}

export type ReadWriteSelectorFamilyOptions<
  T,
  Parameter
> = ReadOnlySelectorFamilyOptions<T, Parameter> & {
  set: (
    params: Parameter,
  ) => (
    opts: {
      set: SetRecoilState;
      get: GetRecoilValue;
      reset: ResetRecoilState;
    },
    newValue: T | DefaultValue,
  ) => void;
};

export function selectorFamily<T, Parameter>(
  options: ReadOnlySelectorFamilyOptions<T, Parameter>,
): (params: Parameter) => RecoilValueReadOnly<T>;
export function selectorFamily<T, Parameter>(
  options: ReadWriteSelectorFamilyOptions<T, Parameter>,
): (params: Parameter) => RecoilState<T>;

```

**Comment by csantos42** [comment] 2020-06-01 01:18
hi @jaredpalmer thank you for that! I'm working on the utility types now-- they'll be very similar to what you have above, but with a small change to ensure that the `Parameter` generic param is serializable. I'll also add the types for the async utility functions. 

I'm marking this issue as resolved for now since we have the types over at DefinitelyTyped and they've been deployed to npm. Thanks again!

**Closed by csantos42** 2020-06-01 01:18 UTC

**Comment by csantos42** [comment] 2020-06-01 05:29
FYI the PR that exposes the new utility methods is live: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45206

**Comment by Odonno** [comment] 2020-06-01 08:47
Isn't `default` optional property of an `atom`. Meaning `undefined` by default?

**Comment by nrgapple** [comment] 2021-03-03 17:11
Is there an example of typing an atom effect?

I am trying to type the generic `localStorageEffect` [here](https://recoiljs.org/docs/guides/atom-effects/#local-storage-persistence)

**Comment by drarmstr** [comment] 2021-03-03 22:00
> Isn't `default` optional property of an `atom`. Meaning `undefined` by default?

`default` is required.

**Comment by drarmstr** [comment] 2021-03-03 22:00
@nrgapple - What is the problem you are seeing that does not work?

**Comment by nrgapple** [comment] 2021-03-04 17:40
@drarmstr that is incorrect typescript. I don't know have you would type a function that should also be generic

**Comment by Kordonme** [comment] 2021-03-20 23:27
Thanks for the example @nrgapple. I made a few adjustments and made your example work:

```typescript

const localStorageEffect: <T>(key: string) => AtomEffect<T> = (
  key: string
) => ({ setSelf, onSet }) => {
  const savedValue = localStorage.getItem(key);
  if (savedValue != null) {
    setSelf(JSON.parse(savedValue));
  }

  onSet((newValue) => {
    if (newValue instanceof DefaultValue) {
      localStorage.removeItem(key);
    } else {
      localStorage.setItem(key, JSON.stringify(newValue));
    }
  });
};

export const authenticationInfoState = atom<AuthenticationInfo | null>({
  key: "authenticationInfoState",
  default: null,
  effects_UNSTABLE: [
    localStorageEffect<AuthenticationInfo | null>(LOCAL_STORAGE_KEY),
  ],
});
```
