### ISSUE TITLE
Unbounded memory increase when using recoil

### ISSUE THREAD

**Issue by mihilmy** [facebookexperimental/Recoil#2040] opened 2022-09-28 01:38 UTC
Very basic application using the following logic:

```typescript
  const [exceptions, setExceptions] = useRecoilState(exceptionAtom);

  // Internal Functions
  const poller = () => fetchExceptions().then((exceptionsList) => setExceptions(exceptionsList));
  
// Effects
  React.useEffect(() => {
    poller();
    const interval = setInterval(poller, 30_000);
    return () => clearInterval(interval);
  }, []);
```

The following leads to an unbounded increase in memory over time in both dev and prod build. I will be switching off of Recoil but just wanted to call it out. 

I know this is a bit vague and I dont have any repro links but leaving this here in case anyone runs into this

**Comment by drarmstr** [comment] 2022-09-28 03:39
Duplicate of #954

**Closed by drarmstr** 2022-09-28 03:39 UTC
Labels: duplicate
