### ISSUE TITLE
recoil state not showing in devtools inspector?

### ISSUE THREAD

**Issue by naivefun** [facebookexperimental/Recoil#347] opened 2020-06-18 07:36 UTC
Now I cannot find the state value in the inspector like this:

![image](https://user-images.githubusercontent.com/10683378/84991719-7dec0380-b179-11ea-9316-6559ec354e53.png)

How can I view current state value?

**Comment by drarmstr** [comment] 2020-06-26 21:08
Duplicate of #194

There is not yet an inspector for Recoil State, though we are working on dev tools.  

In the meantime you can setup your own state monitoring with components subscribing to the state you care about or using something like [`useRecoilSnapshot()`](https://recoiljs.org/docs/api-reference/core/useRecoilSnapshot) or [`useRecoilTransactionObserver()`](https://recoiljs.org/docs/api-reference/core/useRecoilTransactionObserver) to monitor all of the `<RecoilStore>` state.  You can also explore `window.$recoilDebugStates` in the debugger in the meantime, though this is undocumented/unstable.

**Closed by drarmstr** 2020-06-26 21:08 UTC
Labels: devtools, question
