### ISSUE TITLE
Observe other values in atom effects

### ISSUE THREAD

**Issue by jacobp100** [facebookexperimental/Recoil#901] opened 2021-02-26 21:32 UTC
I've got one bit of my code that's stuck to using React hooks + a context provider to propagate a single value down. The code in question takes two recoil values, performs some async work on them, and stores the value.

I can't migrate fully to recoil since there's no `get` function in the effects. Maybe something like this could work,

```js
const myState = atom({
  key: 'MyKey',
  default: null,
  effects_UNSTABLE: [
    ({ get, setSelf }) => {
      const value1 = get(value1State)
      const value2 = get(value2State)

      let cancelled = false
      doSomeAsyncTask(value1, value2).then(value => {
        if (!cancelled) setSelf(value)
      })

      return () => { cancelled = true };
    },
  ],
});
```

**Comment by BenjaBobs** [comment] 2021-02-26 21:35
Duplicate of #850 which is itself a duplicate of #707.

**Closed** 2021-02-26 22:47 UTC
Labels: duplicate
