### ISSUE TITLE
Selector returns the same value but triggers component re-renders

### ISSUE THREAD

**Issue by otakustay** [facebookexperimental/Recoil#745] opened 2020-11-18 13:06 UTC
I've created a sandbox here: https://codesandbox.io/s/exciting-solomon-zv9dz

I have an atom of value `{foo, bar}`, on each click to button `bar` is incremented but `foo` should stay the same. Also I created a selector to read the value of `foo` which should always be constant.

By clicking button I find `App` is not rendered (as expected) but `FooValue` is re-rendered, `react-redux`'s `useSelector` has a good behavior to prevent such render, is there a chance that recoil can optimize this situation?

**Comment by drarmstr** [comment] 2020-11-18 22:13
Duplicate of #314

**Closed by drarmstr** 2020-11-18 22:13 UTC
Labels: performance
