### ISSUE TITLE
Internal React warning when using recoil in stable react releases and not experimental

### ISSUE THREAD

**Issue by incepter** [facebookexperimental/Recoil#31] opened 2020-05-15 15:46 UTC
I bootstraped a react app using `create-react-app`, then added `recoil` and just pasted the code from the website demo.

When the app renders for the first time, an internal react warning in console is shown:

```
Warning: Cannot update a component (`he`) while rendering a different component (`CharacterCount`). To locate the bad setState() call inside `CharacterCount`, follow the stack trace as described in https://fb.me/setstate-in-render
    in CharacterCount (at App.js:31)
    in div (at App.js:29)
    in CharacterCounter (at App.js:7)
    in RecoilRoot (at App.js:6)
    in App (at src/index.js:7)
    in StrictMode (at src/index.js:6)
```

![image](https://user-images.githubusercontent.com/8569885/82069311-a8522900-96c2-11ea-85e3-d21c74592377.png)

Updating `react` dependencies to the experimental ones solved the warning.

PS: the issue doesn't occur with `react^16.12` but only with `^16.13.1`

Here is a [codesandbox demo](https://codesandbox.io/s/friendly-hodgkin-4lo03)

So, should we use recoil only with the experimental react release ?

**Comment by incepter** [comment] 2020-05-15 15:52
Here is the full stack trace.
![image](https://user-images.githubusercontent.com/8569885/82070061-be141e00-96c3-11ea-8bec-34e0850ec7ee.png)

I will continue through the tutorial to know the basics and advanced stuff of recoil, if this is not solved I wish I work on it.

**Comment by incepter** [comment] 2020-05-15 17:12
I figure out that this warning was added after the experimental and 16.12 releases.

**Comment by davidmccabe** [comment] 2020-05-15 17:37
Thanks for reporting, I'm currently looking into this.

**Comment by Xiphe** [comment] 2020-05-16 04:59
facing similar issues on 

```
"react": "0.0.0-experimental-33c3af284",
"react-dom": "0.0.0-experimental-33c3af284",
"recoil": "0.0.7"
```

**Comment by Kalyskin** [comment] 2020-05-16 16:58
facing similar issues on
```
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "recoil": "^0.0.7"
```

**Comment by acutmore** [comment] 2020-05-17 10:32
Possible duplication of #12

**Comment by incepter** [comment] 2020-05-17 20:50
> Possible duplication of #12

Yes absolutely a duplicate, didn't notice it.

I do not how to flag this issue as a duplicate.

**Comment by drarmstr** [comment] 2020-05-18 00:59
Duplicate of #12

**Closed** 2020-05-18 01:00 UTC
