### ISSUE TITLE
[docs] Add Example for `useTransactionObservation`

### ISSUE THREAD

**Issue by iamawaisakram** [facebookexperimental/Recoil#138] opened 2020-05-22 09:46 UTC
Hi, Today I started to implement this cool lib, but couldn't find an example for App Wide Observation using useTransactionObservation. Can anyone kindly help me with this, please!

**Comment by acutmore** [comment] 2020-05-22 09:58
Hi @iamawaisakram. There is some information in this PR: #90

**Comment by iamawaisakram** [comment] 2020-05-22 10:01
Thank you @acutmore !

**Comment by drarmstr** [comment] 2020-05-23 07:02
Yeah, I'm planning to post those docs this weekend.  Though, with a heavy disclaimer as that API is under development and will be changing shortly.  I've started prototyping the new API, so we're making progress..

**Comment by drarmstr** [comment] 2020-05-25 06:48
Duplicate of #157

**Closed by drarmstr** 2020-05-25 06:48 UTC
Labels: documentation
