### ISSUE TITLE
Selector with custom set + Typescript

### ISSUE THREAD

**Issue by momentiris** [facebookexperimental/Recoil#652] opened 2020-10-14 09:09 UTC
Hey! Cred for the work that has been put into this, like it alot!

However, I ran in to this situation and don't know how I'm supposed to handle it.

I have an atom: 
```javascript


const ui = atom<types.UIState>({
  key: 'ui',
  default: {
    showMapTooltip: false,
    highlightBooking: undefined,
    highlightTransport: undefined,
    lastClickedPosition: {
      x: undefined,
      y: undefined,
      lat: undefined,
      lon: undefined,
      address: undefined,
    },
    lastFocusedInput: undefined,
  },
})

```

and I have a selector with a custom set: 
```javascript
import { selector } from 'recoil'
import atoms from './atoms'
import reducers from './reducers'
import * as types from './types'

const UIState = selector<types.UIState>({
  key: 'createTransport',
  get: ({ get }) => get(atoms.ui),
  set: ({ set }, action) => {
    set(atoms.ui, (currentState) =>
      reducers.UIState(
        currentState,
        (action as unknown) as types.UIStateReducerAction
      )
    )
  },
})
```

... whos return value I resolve with this reducer:
```javascript
const UIState = (state: types.UIState, action: types.UIStateReducerAction) => {
  switch (action.type) {
    case 'focusInput':
      return { ...state, lastFocusedInput: action.payload }
    ...
  }
}

export default { UIState }
```

And I wish to use this by 'dispatching' to the setter:

```javascript
const [UIState, setUIState] = useRecoilState(selectors.UIState)

const handleClick = setUIState({ type: 'showMapTooltip' })
```

This becomes a problem because I've typed the selector as a ```types.UIState``` which also makes the ```newValue (action) ``` parameter in the custom set of the selector definition expected to be the same type:

```javascript
export interface ReadWriteSelectorOptions<T> extends ReadOnlySelectorOptions<T> {
  set: (
    opts: {
      set: SetRecoilState;
      get: GetRecoilValue;
      reset: ResetRecoilState;
    },
    newValue: T | DefaultValue,
  ) => void;
}
```

Hopefully I've successfully conveyed that I want to be able to resolve the set return value through my reducer, hence want to control which type is expected to go in as an argument to that selector hook. As you can see in the snippet with the selector:
```javascript 
const UIState = selector<types.UIState>({
  key: 'createTransport',
  get: ({ get }) => get(atoms.ui),
  set: ({ set }, action) => {
    set(atoms.ui, (currentState) =>
      reducers.UIState(
        currentState,
        (action as unknown) as types.UIStateReducerAction
      )
    )
  },
})
```
I have to cast the `action` parameter to unknown, and then to the reducer action type. I really don't know how I should do it. 
I can see this being related to #36, but I cant get around how to properly type the argument coming in to the selectors set function.

Perhaps I'm thinking about it wrong. Any help would be very much appreciated!

**Comment by mondaychen** [comment] 2020-10-14 14:33
@csantos42 can you help with this?

**Comment by drarmstr** [comment] 2020-10-14 21:05
@momentiris - The intention is that atoms and selectors share the same interface from the user/hook perspective.  Those only have a single type parameter and we didn't want to complicate it with a second.  We sometimes use the pattern of different selectors for different types.  

For this reducer type pattern, you may want to use a simple hook or `useRecoilCallback()` instead of a writeable selector.  I think we may also want to explore a "reducer" type helper to wrap selectors for managing actions, that's just an idea at this point, though.

**Comment by drarmstr** [comment] 2020-10-14 21:08
Duplicate of #459

**Comment by momentiris** [comment] 2020-10-15 07:28
Thanks for the response. I had some new light shine on the situation from reading the duplicate issues. Thanks for the response!

**Closed** 2020-10-20 19:42 UTC
Labels: duplicate
