### ISSUE TITLE
can Recoil stop update React Component update when atom value still same after update?

### ISSUE THREAD

**Issue by xuzhanhh** [facebookexperimental/Recoil#493] opened 2020-07-22 03:07 UTC
Hey guys! I want to stop rerender Component when atom/selector get the same value after updater. What should I do?

Here's the playground: https://codesandbox.io/s/stoic-resonance-vecxs?file=/src/App.js:758-811

actually, I try to normalize `todoState` in a `atom(todoIdListState)` and `atomFamily(todoState)` mapping in order to avoid updating all `<TodoItem/>`, but when I add a state `filteredTodoIdListState` whitch subscribe `atomFamily(todoState)`, it will cause rerender `<TodoList/>` when I changing one `todoState atom`. How can I stop this rerender? Is there a way like [react useState's internal compare check?](https://github.com/facebook/react/issues/14110#issue-377541927)
Here's the playground with normalize todo: https://codesandbox.io/s/condescending-sinoussi-d3ck0?file=/src/App.js:1853-1861

**Comment by brianc** [comment] 2020-07-22 17:20
It looks like [this commit](https://github.com/facebookexperimental/Recoil/commit/845e0e421782e958e6df21e88e32609b4416b0cd) might address that.

**Comment by drarmstr** [comment] 2020-07-22 22:11
Setting atoms is addressed with #386, limiting re-renders of selectors with the same value is duplicate of #314

**Closed by drarmstr** 2020-07-22 22:11 UTC
Labels: duplicate

**Comment by xuzhanhh** [comment] 2020-07-23 02:49
thanks!
