### ISSUE TITLE
Promises in initialize state doesn't work, example from docs

### ISSUE THREAD

**Issue by polemius** [facebookexperimental/Recoil#204] opened 2020-05-30 18:25 UTC
I'm trying to use the code from [docs](https://recoiljs.org/docs/guides/persistence) but the code to update state in `initializeState` doesn't work with promises.

```js
<RecoilRoot
      initializeState={({ set }) => {
        // this line update the count atom
        // set({ key: "count" }, 100);

        // but in promise it doesn't work:
        Promise.all([1]).then(() => {
          set({ key: "count" }, 100);
        });
      }}
    >
<App />
</RecoilRoot>
```

Here the demo: https://codesandbox.io/s/strange-wescoff-pwvih?file=/src/index.js

**Comment by acutmore** [comment] 2020-05-30 20:09
Hi @polemius. I believe this is a duplicate of either #103 or #171

**Comment by drarmstr** [comment] 2020-05-31 00:12
@polemius - The persistence API is currently under development and will change, working on it now..  The `initializeState` callback doesn't support async sets.  Removing that from the docs. (#209) I should probably remove those docs entirely until the API is published..

**Closed by drarmstr** 2020-05-31 00:12 UTC
Labels: documentation

**Comment by polemius** [comment] 2020-06-01 05:05
@acutmore @drarmstr Thanks 👍
