### ISSUE TITLE
TS2322: Type '{ children: Element; }' is not assignable to type 'IntrinsicAttributes & RecoilRootProps'.

### ISSUE THREAD

**Issue by Hanggi** [facebookexperimental/Recoil#1726] opened 2022-04-10 06:40 UTC
The env is React 18 with typescript.

I trying to add <RecoilRoot> to the root of React application.

But it shows:

```
TS2322: Type '{ children: Element; }' is not assignable to type 'IntrinsicAttributes & RecoilRootProps'.
```

**Comment by Hanggi** [comment] 2022-04-10 07:05
It seems about to https://github.com/facebookexperimental/Recoil/pull/1718

**Comment by suren-atoyan** [comment] 2022-04-11 15:05
@drarmstr any updates on this? ☝️

**Comment by mondaychen** [comment] 2022-04-11 15:06
We'll try to merge https://github.com/facebookexperimental/Recoil/pull/1718 today and cut a new release ASAP

**Comment by drarmstr** [comment] 2022-04-11 18:39
Duplicate of #1717

**Comment by drarmstr** [comment] 2022-04-13 03:30
Published 0.7.1

**Closed by drarmstr** 2022-04-13 03:30 UTC
Labels: duplicate, TypeScript
