### ISSUE TITLE
The component rerender even the value from selector is not change

### ISSUE THREAD

**Issue by thanhlmm** [facebookexperimental/Recoil#924] opened 2021-03-17 14:46 UTC
## How to reproduce
https://codesandbox.io/s/recoil-test-8jove?file=/src/App.js

- I have an atom to keep track an array of item - `AtomA`
- A selector to validate the length of above array - `SelectorB`

So every time I add new item to `AtomA` but the `SelectorB` still return same result, the component subscribe to it always rerender

**Comment by BenjaBobs** [comment] 2021-03-17 14:54
This is possibly fixed by https://github.com/facebookexperimental/Recoil/pull/749 and will be available when `0.2.0` drops.

**Comment by thanhlmm** [comment] 2021-03-17 14:56
@BenjaBobs Thanks. But when it will be released?
It currently impact my app a lots

**Comment by BenjaBobs** [comment] 2021-03-17 15:04
Last I heard it need a bit more testing, but soonish I think.

**Comment by drarmstr** [comment] 2021-03-17 19:45
Duplicate of #314.

This optimization is provided in #749.  However, that fix is not exposed yet because it still has a bug interacting with React Suspense.  Need someone who has time to help debug it..

**Closed by drarmstr** 2021-03-17 19:45 UTC
Labels: duplicate, performance
