### ISSUE TITLE
Could ReadWriteSelector has each different type argument for read and write?

### ISSUE THREAD

**Issue by hachibeeDI** [facebookexperimental/Recoil#589] opened 2020-09-18 05:49 UTC
Occasionally I'd like to have a selector have different type argument like the title.
For instance, a selector which is abstraction of data access can return nullable value but setter shouldn't.

It's convenient if I could write a selector like `selector<R, W>(...)`.
So far I'm using a wrapper in my project like below:

```typescript
type ReadWriteCustomOpt<R, W> = {
  key: string;

  get: (opts: {get: GetRecoilValue}) => Promise<R> | RecoilValue<R> | R;
  set: (
    opts: {
      set: SetRecoilState;
      get: GetRecoilValue;
      reset: ResetRecoilState;
    },
    newValue: W | DefaultValue,
  ) => void;
};

/**
 * Example:
 * ```
 * export const someSelector = readWriteSelector<Maybe<User>, User>({ ... });
 * ...
 * // use `writer` property to set value.
 * const setSomething = useSetRecoilState(timelineSelector.writer);
 * const something = useRecoilValue(timelineSelector.reader);
 * ```
 */
export function readWriteSelector<R, W>(opt: ReadWriteCustomOpt<R, W>) {
  const {key, get: customGetter, set: customSetter} = opt;
  const writer = selector<W>({
    key: `custom-${key}-writer`,
    get: ({get}) => {
      throw new Error('Set only selector');
    },
    set: (opt, newVal) => customSetter(opt, newVal),
  });
  const reader = selector<R>({
    key: `custom-${key}-reader`,
    get: (opt) => customGetter(opt),
  });

  return {writer, reader};
}
```

(I'm sorry it's written in TypeScript... I haven't caught up flow-type well yet)

It looks awkward a bit though works good for my purpose.
I'd like to ask is it acceptable by Recoil's concept?

Thanks!

**Comment by drarmstr** [comment] 2020-09-18 18:59
Duplicate of #459 

We want to keep the interface of selectors and atoms the same when using them from hooks and avoid the extra complexity of what it would mean for propagating multiple generics around and trying to enforce that they are always the same for atoms.

What you want can be accomplished by using stacked selectors to represent different types.  A wrapper like you are using here is a perfectly reasonable solution for providing the functionality you want without complicating the core API.

**Closed by drarmstr** 2020-09-18 18:59 UTC
