### ISSUE TITLE
how to force selector recompute

### ISSUE THREAD

**Issue by weird94** [facebookexperimental/Recoil#536] opened 2020-08-27 13:02 UTC
when using async selector, how can i make selector recompute.

**Comment by ohansemmanuel** [comment] 2020-08-28 17:18
What do you mean by recompute? @weird94 

If the selector is computed based off of an atom, changing that atom forces a computation. If its dependent on some other state entity in the data-flow graph I.e retrieved via the “get” function, then changing the value returned forces a re-computation. 

Are you specifically referring to invalidating the cache and getting recomputed async fetch?

**Comment by weird94** [comment] 2020-08-31 06:20
Are you specifically referring to invalidating the cache and getting recomputed async fetch?
-----
Yes.  @ohansemmanuel

**Comment by drarmstr** [comment] 2020-08-31 22:26
Duplicate of #422

**Closed by drarmstr** 2020-08-31 22:26 UTC
Labels: duplicate
