### ISSUE TITLE
`Warning: Cannot update a component from inside the function body of a different component.` when using selector

### ISSUE THREAD

**Issue by djwglpuppy** [facebookexperimental/Recoil#94] opened 2020-05-18 06:23 UTC
I get that warning anytime I try and get the derived value of a `selector`.  (I am on the latest version of React)

warning: `Warning: Cannot update a component from inside the function body of a different component.`

... using the atoms with a `useMemo` does not trigger the warning, fyi.

Recoil State:

```js
export const detail = {
    name: atom({
        key: 'detail.name',
        default: ''
    }),
    platform: atom({
        key: 'detail.platform',
        default: ''
    }),
    valid: selector({
        key: 'detail.valid',
        get: ({ get }) => get(detail.name) !== '' && get(detail.platform) !== ''
    })
};
```

Component:

```export default function DetailInformation() {
    const valid = useRecoilValue(detail.valid);

    return (<div className='detail'>
        <h1>Detail Information</h1>
        <div><b>Valid:</b> {valid ? 'Yes' : 'No'}</div>
    </div>);
}
```

**Comment by acutmore** [comment] 2020-05-18 09:40
Hi @djwglpuppy, I think this is a duplicate of #12

**Closed** 2020-05-18 15:54 UTC
