### ISSUE TITLE
When Recoil is going to stop being experimental?

### ISSUE THREAD

**Issue by manyopensource** [facebookexperimental/Recoil#691] opened 2020-10-30 04:39 UTC
Is it ready for production? Are there companies that use Recoil in production?

**Comment by BenjaBobs** [comment] 2020-10-30 06:46
We use Recoil in production and are very excited about it! 😄  no problems so far.

**Comment by wojtekmaj** [comment] 2020-10-30 11:41
Duplicate of #610

**Comment by manyopensource** [comment] 2020-10-30 12:47
@BenjaBobs Can you tell a bit more, what kind of project is it (primarily interested in its complexity)!

**Comment by BenjaBobs** [comment] 2020-10-30 13:17
It's similar to a stock-trading app where customers manage their portfolios and view different slices of data based on time/region/other groupings.

**Comment by BenjaBobs** [comment] 2020-11-02 21:17
I just upgrade to `0.1.2` on my hobby project and I must say I really love how the atom effects allow me to clean up my code: https://github.com/BenjaBobs/HotsTools/commit/8635335ac4dd211e8b0673b586bd30cae70498eb 

Kudos to the team! 😄

**Comment by jainamsha** [comment] 2021-06-13 19:49
I want to use recoil to manage navigation for my application in production, is it advisable?

**Comment by valentinbourqui** [comment] 2021-07-07 21:03
This is great to read that @wojtekmaj. But to me what I wanted is to have firstly a confirmation from guys who are working on this projet that this projet will not stop in few month years... and secondly to know if there is any official release date for a version 1 and not a beta/experimental.

**Comment by meglio** [comment] 2021-07-08 06:34
Considering there are 128 open issues, including `help`, `performance` and `help-wanted`, I'd not use it in production. Just for a comparisong, a production ready library like `zustang` only has less than 30 open issues, zero bugs.

I'm too willing to start using Recoil in production, just need some "Yes" from the library authors first.

**Comment by phuctm97** [comment] 2021-12-30 02:52
I used recoil in my product in production and love it! But it's actually a concern not seeing the library author replying here

**Comment by drarmstr** [comment] 2022-01-21 23:21
Please see discussion in #1495

**Closed by drarmstr** 2022-01-21 23:21 UTC
