### ISSUE TITLE
[recoil-sync] Expose `updateItems` from `listen` property?

### ISSUE THREAD

**Issue by FezVrasta** [facebookexperimental/Recoil#2025] opened 2022-09-21 18:12 UTC
I want to update multiple items at once through the `listen` `RecoilSync` property but it only exposes `updateItem` and `updateAllKnownItems`, why isn't `updateItems` exposed too?

I'd like to avoid the additional overhead of creating one Map for each update as I already have a Map that I could directly send to `updateItems`.

**Comment by drarmstr** [comment] 2022-09-23 21:49
Duplicate of #2017

**Closed by drarmstr** 2022-09-23 21:49 UTC
Labels: duplicate
