### ISSUE TITLE
Access atom/selector without hooks?

### ISSUE THREAD

**Issue by naivefun** [facebookexperimental/Recoil#76] opened 2020-05-17 14:02 UTC
Is there such apis for pure services?

**Comment by acutmore** [comment] 2020-05-17 16:40
Hi @naivefun. I've looked through the exports in [Recoil.js](https://github.com/facebookexperimental/Recoil/blob/master/src/Recoil.js) and [RecoilUtils.js](https://github.com/facebookexperimental/Recoil/blob/master/src/RecoilUtils.js). From what I can tell the only way to access an Atom/Selector value is using the hooks.

The values are stores in a React context, so the only place they can be accessed is a component inside a `<RecoilRoot>` provider.

**Comment by lishine** [comment] 2020-05-17 22:46
Duplicate of #73

**Comment by drarmstr** [comment] 2020-05-18 00:48
Correct.  Unlike many other state management systems there is no "global" state.  The state is associated with the particular render tree for the particular execution of a function component.  So, we use hooks to work with that React context.  This will allow us to be compatible with the future of React as we move towards concurrent rendering, Suspense, &c.

**Closed by drarmstr** 2020-05-18 00:48 UTC
