### ISSUE TITLE
Recoil freezes passed object, causes error in Firebase

### ISSUE THREAD

**Issue by theninthsky** [facebookexperimental/Recoil#1412] opened 2021-11-12 07:55 UTC
recoil: 0.5.2

Please refer to this issue:

https://github.com/firebase/firebase-js-sdk/issues/5722

The following (partial) segment of code:

```
import { useSetRecoilState } from 'recoil'
import { signOut } from 'firebase/auth'

import { userState } from './atoms'
import { auth } from 'firebase-app'
.
.
const setUser = useSetRecoilState(userState)
.
.
onAuthStateChanged(getAuth(app), user => setUser(user))
.
.
signOut(auth)
```

Causes the following error (thrown by signOut function):

```
TypeError: Cannot assign to read only property 'currentUser' of object '#<AuthImpl>'
    at AuthImpl.directlySetCurrentUser
```

This error, however, does not happen when a deep copy is passed to setUser:

`onAuthStateChanged(auth, user => setUser(cloneDeep(user)))`

It seems that recoil freezes passed objects for some reasons.

**Comment by mondaychen** [comment] 2021-11-12 18:42
Yes, it's unexpected that the objected stored in a recoil atom is mutated without a recoil hook. To help detect bugs Recoil will freeze objects stored in atoms in development mode. See https://recoiljs.org/docs/api-reference/core/atom

duplicate of #1053

**Closed** 2021-11-12 18:43 UTC

**Comment by theninthsky** [comment] 2021-11-13 16:13
Thanks!

**Comment by drarmstr** [comment] 2022-04-21 18:05
Duplicate of #794

**Comment by visheshyte** [comment] 2024-03-24 05:34
@theninthsky hey, I don't know how you fixed your problem with firebase signout thing few year ago XD.. but I am stuck in the same issue now : ( . I am using recoil and firebase.. and I am trying to manage user auth with the recoil atom and the problem is I don't understand how recoil can manipulate the auth object which is entirely controlled by the firebase broo.. tell me.
