### ISSUE TITLE
Memoization of selectorFamily values?

### ISSUE THREAD

**Issue by ryansolid** [facebookexperimental/Recoil#211] opened 2020-05-31 03:28 UTC
I'm not clear if this is intended, something missing in the docs, or me just making a feature request. 

I was working on the JS Framework Benchmark which is basically a large TodoList. It consists of a large global list of items, and single selected state that holds the row id to indicate a row has been clicked on.

I noticed that `selectorFamily` while technically working wasn't saving me execution for selection. Writing a selector to do this more or less was trivial:

```js
const selectedState = atom({
    key: "selectedState",
    default: null,
  }),
  rowSelectedState = selectorFamily({
    key: "rowSelectedState",
    get: (id) => ({ get }) => get(selectedState) === id,
    set: (id) => ({ set }) => set(selectedState, id),
  })
```
This was good because it never triggered list reconciliation in the parent. However, what this meant is every time `selectedState` changed every row component would re-render. I'm gathering it just looks that selectedState has changed and pushes all updates through that depend on it. I was expecting if `get` returned the same value (a boolean in this case) it would not bother re-rendering. 

I was trying to do something similar with updating row data (a label) in the list data that is only read from a row and it of course triggered full list reconciliation every time. Since the `dataState` is what is being iterated over in the view.

```js
const dataState = atom({
    key: "dataState",
    default: [],
  }),
  rowLabelState = selectorFamily({
    key: "rowLabelState",
    get: (id) => ({ get }) => get(dataState).find((d) => d.id === id).label,
  });
```

I then tried using an `atomFamily`. In a sense this fixed this since I was pulling the data out of the list. But I couldn't figure out how to update it in a feasible way outside of each row Component (from the parent) since the test runner iterates through data doing updates so using Hooks would be no good on a per atom basis. I don't believe `atomFamily` is the right solution here. `selectorFamily` acting as lenses on the root data makes more sense for this case but we need a way of memoizing component updates so that it doesn't simply trigger when the base state updates. (That being said doing a find against every row is probably not very efficient anyway, and normalizing into an object would improve perf here), but it still stands it would be great if this didn't lead to the whole tree re-rendering every time.

**Comment by drarmstr** [comment] 2020-05-31 05:05
We don't yet suppress updates when the updated value is the same, but that is on our roadmap.

As you point out, using an `atomFamily` for the individual row data can help with the subscriptions since each is an independent piece of state that can be subscribed to.  If you want to read data from a set of atoms for the list you can use [`waitForAll`](https://recoiljs.org/docs/api-reference/utils/waitForAll):

```jsx
const itemsState = atomFamily({
  key: 'Items',
  default: {...},
});

function ListDisplay() {
  const listIDs = [1, 2, 3];
  const listData = useRecoilValue(waitForAll(listIDs.map(itemsState)));
  ...
}
```

**Comment by acutmore** [comment] 2020-05-31 10:33
Hi @ryansolid 

While the Recoil team work on their plans to suppress updates when values stay the same, this pattern might achieve a similar outcome. Moving the dependency out of the selector and into a component. Admittedly less elegant I know.

```javascript
const selectedRow = atom(...); // track the currently selected ID
const rowData = atomFamily(...); // split each row into a seperate atom

/**
 * When the `selectedRow` changes this component will render and update the atoms.
 * Causing only the two affected rows to then render.
 * Total components rendered === 3
 */
function KeepSelectionUpdated() {
    const selectedId = useRecoilValue(selectedRow);
    const previousId = usePrevious(selectedId); // https://usehooks.com/usePrevious/
    const updateRow = useRecoilCallback(({set}) => {
        set(rowData(previousId), (value =>  ({ ...value, selected: false })))
        set(rowData(selectedId), (value =>  ({ ...value, selected: true })));
    }, [selectedId, previoudId])

    useEffect(() => {
        if (selectedId !== previousId) {
            updateRow();
        }
    }, [selectedId, previousId]);

    return null;
}

function List() {
    return <>
        <KeepSelectionUpdated />
        {listIds.map(id => <ListItem id={id} />)}
    </>
}
```

**Comment by ryansolid** [comment] 2020-05-31 21:31
That is pretty reasonable. If I was doing something realworld I don't see much issue there. I think there are limits in the benchmark what I can do to represent the data and it still keep the same spirit of the other implementations. Still I will stew on this. The idea of an isolated component managing the top-level state could do the trick. Thanks.

**Comment by drarmstr** [comment] 2020-06-13 05:40
Duplicate of #314

**Closed by drarmstr** 2020-06-13 05:40 UTC
Labels: enhancement
