### ISSUE TITLE
loading failure on IE11

### ISSUE THREAD

**Issue by toysmoon** [facebookexperimental/Recoil#1113] opened 2021-07-12 14:24 UTC
my project using
- next.js
- recoil

.babelrc
```json
{
  "presets": [["next/babel", { "preset-env": { "targets": "ie 11" } }]],
  "plugins": [
    "@babel/plugin-transform-parameters",
    "@babel/plugin-transform-destructuring"
  ]
}
```

when I build next.js project, I have an Error on IE 11
```
SCRIPT1010 : Expected identifier
0a301732-d3c0239a248636b1ad05.js (1,291)
```

My guess is that the code below is not being built properly.

`src/util/polyfill/recoverableViolation.js`

- before build: 
```typescript
function recoverableViolation(
  message: string,
  projectName: 'recoil',
  {error}: {error?: Error} = {},
): null {
  if (__DEV__) {
    console.error(message, error);
  }
  return null;
}
```
- after build:
```javascript
var i=function(e,t,{error:n}={}){return null};
```

after built code still have `default parameter`, `rename property`
i want transform `default parameter`, `rename property`
like this:
```
var i=function(e,t,k){var k2 = k || {}; var n = k2.error;return null};
```

**Comment by mondaychen** [comment] 2021-07-12 15:21
If I read it right, this is babel question rather than a recoil question.
Does the transforming works for your own code when you have destructuring / renaming?

**Comment by toysmoon** [comment] 2021-07-12 15:49
@mondaychen oh, sorry I will question to babel comunity
When I use destructuring / renaming in next.js code, the transforming  works well.

**Comment by drarmstr** [comment] 2021-07-29 03:57
Duplicate of #1073?

**Closed by drarmstr** 2021-07-29 03:57 UTC
Labels: duplicate
