### ISSUE TITLE
[Question] should make selector key to be optional?

### ISSUE THREAD

**Issue by markstock7** [facebookexperimental/Recoil#458] opened 2020-07-09 05:27 UTC
Name selector sometime can be difficult，we may create anonymous selector in hoc pattern, or renderProps pattern

```javascript
const dimensionAtom = atom({ key: 'dimensions', defaultValue: [] })
function DimensionHoc(Component) {
    const filteredDimensions = selector({ 
       get: ({get}) => {
            return get(dimensionAtom).filter(_ => _) // do something to dimensions
       }
   });
   return function Hoc() {
       const dimensions = useRecoilState(filteredDimensions)
       return <Component dimensions={dimensions} />
   }
}
```

**Comment by drarmstr** [comment] 2020-07-09 06:43
Duplicate of #317

**Closed by drarmstr** 2020-07-09 06:43 UTC
Labels: duplicate
