### ISSUE TITLE
Double renders

### ISSUE THREAD

**Issue by dsathyakumar** [facebookexperimental/Recoil#960] opened 2021-04-08 14:54 UTC
Hi,

I'm seeing components being rendered twice upon setting the initial state. Is this the intended behavior for Functional Components?

https://codesandbox.io/s/festive-shtern-c1rz3?fontsize=14&hidenavigation=1&theme=dark

**Comment by dsathyakumar** [comment] 2021-04-08 14:55
The console.logs for <TextInput> and <CharacterCount> get logged twice. Is this behavior intended ?
Can't the initial state be used in the 1st render itself ?

**Comment by bryan-hunter** [comment] 2021-04-08 15:15
there is a fix in place, but it's behind a feature flag - see https://github.com/facebookexperimental/Recoil/issues/314

apparently there's an edge case they are resolving before releasing it fully, but you can patch-package to expose that feature flag for yourself and turn it on.

**Comment by drarmstr** [comment] 2021-04-12 20:01
Duplicate of #820

**Comment by drarmstr** [comment] 2021-04-12 20:01
The initial render is also addressed with experimental version of React with Concurrent Mode enabled.

**Closed by drarmstr** 2021-04-12 20:01 UTC
Labels: duplicate
