### ISSUE TITLE
Best practice for handling data re-initialization

### ISSUE THREAD

**Issue by hachibeeDI** [facebookexperimental/Recoil#537] opened 2020-08-28 08:41 UTC
Hello Recoil team,

I'd like to ask the standard of way to handling remote data lifecycle in Recoil.
Here is quick example below:

```typescript
import {atom, selector, useRecoilValue, RecoilRoot, useRecoilState, useResetRecoilState} from 'recoil';
import React, {useEffect} from 'react';

type NeedInit<T> = {needInitialization: true};
type Succeed<T> = {needInitialization?: false; val: T};
type Refreshable<T> = NeedInit<T> | Succeed<T>;

type User = {name: string};

const userStore = atom<Refreshable<User>>({key: 'user-store', default: {needInitialization: true}});

const userSelector = selector({
  key: 'user-selector',
  get: ({get}) => get(userStore),
});

function InitUserEffect() {
  const [userState, setUserState] = useRecoilState(userStore);
  useEffect(() => {
    (async () => {
      const {needInitialization: needRefresh} = await userState;
      if (needRefresh) {
        // async request dummy
        const fetched = new Promise((resolve: (val: Succeed<User>) => void, reject) => {
          setTimeout(() => resolve({val: {name: 'sample user'}}), 2500);
        });
        // in type definition, SetterOrUpdater doesn't accept Promise... but works
        setUserState(fetched);
      }
    })();
  }, [userState]);

  return null;
}

function CurrentUserInfo() {
  const user = useRecoilValue(userSelector);
  if (user.needInitialization) {
    return <div>Loading...</div>;
  }
  return (
    <div>
      <div>{user.val.name}</div>
    </div>
  );
}

function ResetUserButton() {
  const resetter = useResetRecoilState(userStore);
  return <button onClick={resetter}>reset</button>
}

function MyApp() {
  return (
    <RecoilRoot>
      <h1>hogeegge</h1>

      <React.Suspense fallback={<div>Loading...</div>}>
        <InitUserEffect />
        <CurrentUserInfo />
      </React.Suspense>
      <ResetUserButton />
    </RecoilRoot>
  );
}
render(<MyApp />, document.getElementById('app'));
```

(Async selector getter could make this sample simple, but I need to store remote data as a atom.)

It looks awkward for me... so I have some question.

- Shouldn't I pass a Promise to `SetterOrUpdater`?
- Any plans `Loadable` supports status like `notAsked`?

- Otherwise, have I missed something to implement the pattern?

Thanks!

### Env

```
    "typescript": "^4.0.2",
    "recoil": "^0.0.10",
```

**Comment by drarmstr** [comment] 2020-09-01 00:13
Duplicate of #237 

There is a feature request to support explicitly setting an atom to a `Promise` (#237).  The upcoming Atom Effects API may also be useful to co-locate the synchronization logic with the atom definition to avoid maintaining global components like `< InitUserEffect>`

**Closed by drarmstr** 2020-09-01 00:13 UTC
Labels: duplicate
