### ISSUE TITLE
Calling set multiple times on same atom inside a selector won't give the updated value of the atom

### ISSUE THREAD

**Issue by Busin-Riccardo** [facebookexperimental/Recoil#644] opened 2020-10-10 17:17 UTC
I have a case where a selector will set multiple atom values and in some cases it needs to set the value of the same atom multiple times.

Example:
```
const mySelector = selector({
   key: 'key',
   set: ({ get, set }) => {
       set(myAtom, (value: string[]) => value.filter(myFilter))
       ...some logic
       set(myAtom, (value: string[]) => [...value, valueToAdd])
   }
})
```
Note that the actual code is using atomFamily and that's the reason why it could call set with the same atom multiple times

In the second call to set the passed value is still the old unfiltered one. Is this the expected behaviour? If so is there a workaround ?

Hope I've made it clear. Let me know if I can help in any way.

**Comment by drarmstr** [comment] 2020-10-13 23:16
Yes, this is an issue that only seems to affect selector set.  (Duplicate of #618).  A workaround could be using `useRecoilCallback()`.

**Closed by drarmstr** 2020-10-13 23:16 UTC
Labels: duplicate
