### ISSUE TITLE
hmr update atom dont work

### ISSUE THREAD

**Issue by shaoqiwang-fe** [facebookexperimental/Recoil#1192] opened 2021-08-27 03:33 UTC

**Comment by drarmstr** [comment] 2022-08-18 19:22
@shaoqiwang-fe - We've made some fixes for React Refresh which replaces HMR.  Can you please re-open with a reproducer if you have an example that does not work?

**Comment by drarmstr** [comment] 2022-08-18 19:22
Duplicate of #1404

**Closed by drarmstr** 2022-08-18 19:22 UTC
Labels: pending
