### ISSUE TITLE
Duplicate atom key when i use Nextjs Framework 

### ISSUE THREAD

**Issue by neerajcodes** [facebookexperimental/Recoil#1078] opened 2021-06-19 16:08 UTC
### Here is my error with Nextjs Framework 
 This error comes in my console 
```

Duplicate atom key . This is a FATAL ERROR in
production.

```
Any solution of this problem

**Comment by nikhilag** [comment] 2021-06-20 03:50
This seems to be a duplicate of https://github.com/facebookexperimental/Recoil/issues/733

**Comment by csantos42** [comment] 2021-06-21 07:45
Closing in favor of duplicate #733 -- see that issue for a workaround and discussion

**Closed by csantos42** 2021-06-21 07:45 UTC
