### ISSUE TITLE
Components being re-rendered even when recoilstate value is the same

### ISSUE THREAD

**Issue by cybervaldez** [facebookexperimental/Recoil#340] opened 2020-06-17 13:55 UTC
Is this intentional? Here's a sandbox:
https://nhcpy.csb.app/

**Comment by Shmew** [comment] 2020-06-17 13:58
See #314

**Comment by cybervaldez** [comment] 2020-06-17 16:17
To those that need a very quick work around for this just wrap your component with useMemo.

e.g return useMemo(()=><>{atomValue}</>, [atomValue])

**Comment by drarmstr** [comment] 2020-06-17 22:42
Duplicate of #314

**Closed by drarmstr** 2020-06-17 22:42 UTC
Labels: duplicate, enhancement
