### ISSUE TITLE
Cannot assign to read only property 'width' of object '#<Object>'

### ISSUE THREAD

**Issue by farfloat** [facebookexperimental/Recoil#1716] opened 2022-04-07 04:44 UTC
## Reproduce Code
[Reproduce repo here](https://github.com/farfloat/video-dev)

## Error display
<img width="720" alt="Screenshot 2022-04-07 at 13 37 02" src="https://user-images.githubusercontent.com/100505566/162121094-685d9b98-f9bb-4d8e-8825-42c34f0cc310.png">

I push the button (Show Video) and  display video but got error above...

I think read only value cases this error.
someone got through ??

### environment
-     "recoil": "^0.7.0",
-     "twilio-video": "^2.21.1"

**Comment by csantos42** [comment] 2022-04-07 06:42
Possible duplicate of #794 , I think type additions in #1679 will help here if that's the case

**Closed** 2022-04-09 03:38 UTC
Labels: duplicate
