### ISSUE TITLE
Generated keys?

### ISSUE THREAD

**Issue by shelbyspeegle** [facebookexperimental/Recoil#1782] opened 2022-05-11 14:23 UTC
Have you considered removing the need for developers to supply their own key to each atom / selector and have it be generated by recoil in the background? Is this a bad idea 🤔 ?

After failing to update the `key` prop after duplicating an atom several times and realizing its potential to wreak havoc, combined with the what feels like boilerplate it adds to the definition I was curious if this was on the radar or if you have thought about why this is a bad idea.

**Comment by drarmstr** [comment] 2022-05-11 18:20
There were a few reasons:
* Label for debugging tools.  However, this could be optional.
* Stable key when atoms are persisted beyond lifetime of module.  However, this is less of a concern now as libraries like `recoil-sync` have gone with a separate namespace for keys for persistence, though they do default to the atom key.
* Thus the primary remaining driving factor is for React Fast Refresh.

Duplicate of #378

**Closed by drarmstr** 2022-05-11 18:20 UTC
Labels: duplicate

**Comment by shelbyspeegle** [comment] 2022-05-11 18:34
Thanks!
