### ISSUE TITLE
Warning: Cannot update a component (`Batcher`) while rendering a different component

### ISSUE THREAD

**Issue by ohansemmanuel** [facebookexperimental/Recoil#518] opened 2020-08-11 11:15 UTC
### What's the Problem? 
There's a likelihood I may be doing something wrong, however, I reckon this is related to this [React issue](https://github.com/facebook/react/issues/18178). It appears Recoil tries to re-render a subscribed component while its parent is being rendered. This seems to happen when a loading state is handled via Suspense. 

*React version: 16.13.1* 

### Do you have screenshots of the error? 
![CleanShot 2020-08-11 at 13 12 10@2x](https://user-images.githubusercontent.com/10930234/89890902-7161b580-dbd4-11ea-9312-12edfb569826.png)

![CleanShot 2020-08-11 at 13 12 40@2x](https://user-images.githubusercontent.com/10930234/89890911-745ca600-dbd4-11ea-8f76-52e711459b32.png)

### Got a demo app to reproduce the error? 
Please see this [codesandbox](https://codesandbox.io/s/charming-dream-gh3bu?file=/src/App.js). I advice cloning to your local machine to view the error and follow the stack trace. 

### ⚠️ Update
Handling the loading state in the demo app above via `useRecoilValueLoadable` doesn't seem to throw the same error. Using Suspense does.

**Comment by drarmstr** [comment] 2020-08-11 17:15
Duplicate of #12

**Closed by drarmstr** 2020-08-11 17:15 UTC
Labels: duplicate

**Comment by davidh99720** [comment] 2021-08-18 18:31
I have the same issue. It is caused by setting pageTitle (displayed in explorer tab and history) in each component after routing using recoil. Fixed after centralizing the pageTitle logic in the root of component where pageTitle is rendered.

**Comment by swagasoft** [comment] 2022-05-20 18:39
I had the same using recoil in react, I've searched and real all the above comments with no success. I fix the error by wrapping the interaction with recoil using usEffect. like below 

`import { ResetItemToEdit} from "../store/itemAtom";

function SampleComponent(){
const resetItemToEdit = ResetItemToEdit();

  useEffect(()=> {
    resetItemToEdit();
  },[])

}
`

After doing the above, the error disappears.

**Comment by hafizsaab72** [comment] 2022-07-25 13:05
can you please explain the code a little @swagasoft
