### ISSUE TITLE
[Recoil 0.6.0] Postinstall script fails to find `gen-flow-files`

### ISSUE THREAD

**Issue by fguitton** [facebookexperimental/Recoil#1575] opened 2022-01-29 11:57 UTC
Hello everyone,

While attempting to run `yarn install` following an upgrade of `recoil` from `0.5.2` to `0.6.0` it fails to execute the `postinstall` scripts looking for package `gen-flow-files` to build. This is likely because it is listed as a `devDependencies` in the final NPM package.

https://github.com/facebookexperimental/Recoil/blob/69acb214a36b70e0f28018f22f02ae6c2098cf62/package.json#L20

It fails as follows:
```
> yarn install
yarn install v1.22.17
$ node ./scripts/hintYarn.js
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/5] ⠂ core-js
[2/5] ⠂ recoil
[3/5] ⠂ @parcel/watcher
[4/5] ⠂ cypress
error C:\Repos\secretarium\node_modules\recoil: Command failed.
Exit code: 1
Command: cd ./node_modules/gen-flow-files && yarn install && yarn build
Arguments:
>
```

Considering it seems to be only an exercise to override publishing helper tool called via `npx`, I imagine there is an easy way forward. It's a PR I could make, but I don't know how your team would prefer done.

Hopefully there is a resolution coming into a `0.6.1` soon !
As always, thank you very much for all the work on this repo !

🚀

**Comment by gurkerl83** [comment] 2022-01-29 13:22
Duplicate of https://github.com/facebookexperimental/Recoil/issues/1541

**Closed** 2022-01-29 14:28 UTC
