### ISSUE TITLE
State sharing in different RecoilRoot components

### ISSUE THREAD

**Issue by daliusd** [facebookexperimental/Recoil#414] opened 2020-06-29 07:05 UTC
We have situation where we need to share state between different RecoilRoot components. I have not found a way to do that via API so I assume it is not possible to do that. Maybe it would be possible to add argument allowing passing state's instance to RecoilRoot component?

**Comment by mondaychen** [comment] 2020-06-29 14:48
Can you provide more details on why you need to share state between different `RecoilRoot` components, rather than using one `RecoilRoot` to wrap them all?

**Comment by daliusd** [comment] 2020-06-29 15:00
We need to share state between different applications (old project gradually moving to React). There is no way to wrap everything under single RecoilRoot.

E.g. with Redux we can pass store instance to redux Provider components so it would be good if that were possible with Recoil as well.

**Comment by mondaychen** [comment] 2020-06-29 15:24
@drarmstr is this possible yet?

**Comment by adrianbw** [comment] 2020-06-29 18:20
Is this possible using an observer and passing the state setting function in from within the other recoil root?

**Comment by drarmstr** [comment] 2020-06-29 18:46
Related to #140?

**Comment by daliusd** [comment] 2020-06-29 20:20
> Related to #140?

It is probable that solution to #140 might solve this problem as well. IMHO you can mark this as duplicate of #140 now. In case solution to #140 will not be enough then I or someone else can reopen this issue.

**Comment by drarmstr** [comment] 2020-06-29 21:02
Duplicate of #140

**Closed by drarmstr** 2020-06-29 21:02 UTC
Labels: duplicate, enhancement
