### ISSUE TITLE
Selectors without dependencies are cached across multiple RecoilRoots

### ISSUE THREAD

**Issue by ycz** [facebookexperimental/Recoil#650] opened 2020-10-13 23:12 UTC
Hey all! Not sure if this is expected behavior or not, but it seems weird.

If you have a selector which doesn't have any dependencies on the Recoil state, then that selector will be cached even across different `RecoilRoot`s. This behavior differs from the way atoms work, as well as selectors which depend on atoms.

For example:

```js
let backendValue = 0;
const mySelector = selector({
  key: "MySelector",
  get: () => backendValue,
});

const Thing = ({ mockValue }) => {
  backendValue = mockValue;
  const fetchedValue = useRecoilValue(mySelector);
  return <div>Mocked value is {mockValue}; fetched value is {fetchedValue}</div>;
}

export default function App() {
  return (
    <div>
      <RecoilRoot>
        <Thing mockValue={1} />
      </RecoilRoot>
      <RecoilRoot>
        <Thing mockValue={2} />
      </RecoilRoot>
    </div>
  );
}
```

Sandbox: https://codesandbox.io/s/laughing-feynman-prndc?file=/src/App.js

Here, even though the `mockValue` is different between the two `Thing`s, and the two `Thing`s are under different `RecoilRoot`s , the second `Thing` gets the cached value from the first time the selector was loaded:

![image](https://user-images.githubusercontent.com/3461433/95924554-a45b2d80-0d6c-11eb-8799-a8350be08898.png)

Obviously, using multiple RecoilRoots in this way is a bit contrived - the place this is causing an issue for us is in storybook / screenshot testing. We have a number of selectors which fetch from an API and return the value, which are nice because of their compatibility with `Loadable`s and `React.Suspense`. We'd like to mock these APIs with different values to verify that our stories look correct in different cases. 

The problem is that if an API is first mocked once in one story, then mocked with a different value in another story, the selector will still be cached with the value from the first story, even if the two stories use different `RecoilRoot`s. This causes all sorts of problems for our screenshot CI process, which churns through a bunch of stories in a row, and results in loads of errors and perceived changes based on the order it goes through the tests.

---

Side question: As a workaround for while this issue is not fixed and/or if it's intended, I was hoping there might be a way to either imperatively clear the cache of a selector, or mock out the value of a selector directly in tests (instead of mocking out the underlying API). Looking at previous issues such as https://github.com/facebookexperimental/Recoil/issues/422 suggests that the former is not possible - is there a way to do the latter?

**Comment by drarmstr** [comment] 2020-10-13 23:25
Selectors represent "idempotent/pure" functions of derived state.  For a given set of Recoil atom state they should always provide the same result.  So, it should be safe to cache selectors across Recoil Roots if they follow this contract.

Often, people use selectors to represent queries because of the convenient async and React Suspense handling.  But, they sometimes represent queries which results may change with subsequent retries.  One way this can be modeled is by having the selector depend on some counter atom.  You can then increment the counter to force the selector to re-evaluate.  (Duplicate of #422)

**Closed by drarmstr** 2020-10-13 23:25 UTC
Labels: duplicate
