### ISSUE TITLE
Feature request: destroy atom, selector

### ISSUE THREAD

**Issue by xiyangjun** [facebookexperimental/Recoil#1995] opened 2022-09-03 12:16 UTC
Hello, thanks for recoil, simple & powerful!

I am trying to develop a ui library for automatic calculation of ui properties, which is managed by recoil atoms, when the component is destroyed I need to destroy these atoms.
e.g 
```jsx
<Input value="{{$state.user.id}}" />
<Select value="{{$state.user.city}}" options="{{$store.cityList}}" />
<Text info="{{$state.user.id + '-' + $state.user.city}}" />
```
It will generates a lot of atoms and i have to clean it. so I hope to provide the function of destroy
Thanks, Hope recoil is getting stronger and stronger

**Comment by drarmstr** [comment] 2022-09-07 19:39
Duplicate of #758

**Closed by drarmstr** 2022-09-07 19:39 UTC
Labels: duplicate, enhancement
