### ISSUE TITLE
[Feature request] Ability to get cached value while a node is reloading (SWR)

### ISSUE THREAD

**Issue by FokkeZB** [facebookexperimental/Recoil#1443] opened 2021-11-18 18:47 UTC
:wave: We've recently adopted Recoil at Zapier and found ourselves implementing the following hooks:

```ts
import { useRef } from 'react';
import { RecoilValue, useRecoilValueLoadable } from 'recoil';

export const useRecoilValueLoadableSwr = <TRecoil>(
  recoilValue: RecoilValue<TRecoil>
): {
  isLoading: boolean;
  error: unknown;
  contents: TRecoil | undefined;
} => {
  const valueWhileLoading = useRef<TRecoil>();

  const loadable = useRecoilValueLoadable(recoilValue);

  if (loadable.state === 'hasValue') {
    valueWhileLoading.current = loadable.getValue();
  }

  return {
    isLoading: loadable.state === 'loading',
    error: loadable.errorMaybe(),
    contents: valueWhileLoading.current,
  };
};

export const useRecoilValueSwr = <TRecoil>(
  recoilValue: RecoilValue<TRecoil>
): TRecoil => {
  const valueWhileLoading = useRef<TRecoil>();

  const loadable = useRecoilValueLoadable(recoilValue);

  if (loadable.state === 'hasValue') {
    valueWhileLoading.current = loadable.getValue();
    return valueWhileLoading.current;
  }

  if (loadable.state === 'loading') {
    if (typeof valueWhileLoading.current !== 'undefined') {
      return valueWhileLoading.current;
    }

    throw loadable.contents;
  }

  throw loadable.contents;
};
```

The reason we implemented these is that we noticed that while a loadable is loading, we can't get its last known value. Calling `getValue()` [throws its promise](https://github.com/facebookexperimental/Recoil/blob/50e28150e1a435eff25eb8e3d7099b3f42ac5df4/packages/recoil/adt/Recoil_Loadable.js#L146-L148).

This is fine in many cases, in which we (have Suspense) render a loading state. But in other cases, we'd like to only do this when it's loading for the first time, but once we have a value, we prefer to continue rendering that until we have a new one.

Would it be possible to implement this as a native API?

**Comment by drarmstr** [comment] 2021-11-19 00:53
`useTransition()` should provide this functionality.  

Note that this support isn't released yet, but you could try out the experimental support by enabling the `recoil_early_rendering_2021` feature flag [here](https://github.com/facebookexperimental/Recoil/blob/main/packages/recoil/util/Recoil_gkx.js#L15) in the nightly branch.

Duplicate of #759

**Closed by drarmstr** 2021-11-19 00:53 UTC
