### ISSUE TITLE
Having Typed Arrays as value causes error on set. TypeError: Cannot freeze array buffer views with elements

### ISSUE THREAD

**Issue by JohannesKlauss** [facebookexperimental/Recoil#614] opened 2020-09-26 14:35 UTC
Trying to have a Typed Array as a value type for atoms results in an error, when trying to set it.

```
TypeError
Cannot freeze array buffer views with elements
```
Codesandbox: https://codesandbox.io/s/bold-https-883ge

**Comment by drarmstr** [comment] 2020-09-27 06:15
Duplicate of #596 

This should be fixed with #597

**Closed by drarmstr** 2020-09-27 06:15 UTC
Labels: duplicate
