### ISSUE TITLE
unnecessary re-renderings

### ISSUE THREAD

**Issue by suren-atoyan** [facebookexperimental/Recoil#565] opened 2020-09-09 17:50 UTC
Please examine [this](https://codesandbox.io/s/not-so-clear-re-renderings-ltz3n) code snippet.

The content of the snippet is simple and looks like this:

```javascript
import React from "react";

import { atom, useRecoilValue } from "recoil";

const exampleState = atom({
  key: "exampleState",
  default: "some value"
});

export default function App() {
  const value = useRecoilValue(exampleState);

  console.log("check render");  // it logs 4 times

  return <div>{value}</div>;
}
```

There is nothing special (I guess), one `atom` and one `useRecoilValue` inside the only component. The problem is that the `console.log` that we have in the component logs 4 times 

`useRecoilValue` (without updating the atom) re-renders the component (which uses it) 4 times in the beginning. If we change our code a little bit to have further updates of the atom we can see 2 more logs after each update 😕 

```javascript
import React, { useEffect } from "react";

import { atom, useRecoilState } from "recoil";

const exampleState = atom({
  key: "exampleState",
  default: "some value"
});

export default function App() {
  const [value, setValue] = useRecoilState(exampleState);

  useEffect(() => {
    const timerId = setInterval(() => {
      setValue("other value");
    }, 2000);

    return () => clearInterval(timerId);
  }, [setValue]);

  console.log("check render"); // it logs 4 times at the beginig
  // plus 2 more logs after atom's every update

  return <div>{value}</div>;
}
```

[Here](https://codesandbox.io/s/not-so-clear-re-renderings-2-gb7zl?file=/src/App.js:0-574) is the snippet for this one.

In the ideal (normal) case I suspect to see one log (with 'some value') and after about 2 seconds one more log (with 'other value') and that's all because further updates don't change the value.

I've found [this](https://github.com/facebookexperimental/Recoil/issues/314) issue and some others related to it, but they are about `selector` optimization. Here we have not any `selector`, there is just one `atom` and its usage in the component (via `useRecoilValue`/`useRecoilState`)

**Comment by drarmstr** [comment] 2020-09-09 19:39
Duplicate of #307

@suren-atoyan - React strict mode will perform extra renders to help catch side-effects (#75) are you using that?  We also have added some improvements to reduce extra renders with Recoil.  (#307) Do you see similar behavior with the Recoil master branch and without React strict mode?

**Closed by drarmstr** 2020-09-09 19:39 UTC

**Comment by suren-atoyan** [comment] 2020-09-09 20:43
Thank you for your reply @drarmstr. I would like to check it in the Recoil master branch, but I couldn't manage to build it properly. `yarn build` gives me `es`, `cjs` and `umd` folders. I tried to do import from all of them but got the same error - `Error: This component must be used inside a <RecoilRoot> component.` (it works when I do import from node_modules (from version 0.0.10)). So, maybe I did something wrong, if there is a doc about the build process or you can tell me the steps, I'll check it.

Also, you were right, I forgot about `React.StrictMode` case, but it causes only half of the re-renders.

**Comment by drarmstr** [comment] 2020-09-09 20:49
`yarn build` then `yarn pack` can produce an NPM package which you can use locally.  Though, I think it may have some issues with https://github.com/facebookexperimental/Recoil/commit/3fc140a92b66f2bf818daed61da8102963060437 backed out while we were fixing https://github.com/facebookexperimental/Recoil/commit/f81e844ee95e713894387de7e8a8d0894c69efa0

**Comment by suren-atoyan** [comment] 2020-09-10 08:38
Hi @drarmstr. Let me show you what I did and what is the result:

1) folder `/Recoil` is the master branch of the recoil repo (HEAD is at 565878b)
2) folder `/Project` is a playground (a CRA application)
3) `~/Recoil$`
- `yarn`
- `yarn build`
- `yarn pack`
4) `~/Recoil$` unzip `recoil-v0.0.11.tgz`
5) `~/Recoil$`
- `cd package`
6) `~/Recoil/package$` change package name (in `package.json`) to `recoil-next`
7) `~/Recoil/package$`
- `yarn link`
8) additionally I removed `node_modules` from `~/Recoil` to avoid react duplications in application
9) `~/Project$`
- `yarn link recoil-next`
10) and here is my `App.js` in `~/Project$`

App.js
```javascript
import React from 'react';

import { atom, useRecoilValue } from 'recoil-next/cjs/recoil';
// import { atom, useRecoilValue } from 'recoil';

const exampleState = atom({
  key: 'exampleState',
  default: 'some value',
});

function App() {
  const value = useRecoilValue(exampleState);

  console.log('check renders'); // logs 2 times

  return (
    <div>
      {value}
    </div>
  );
}

export default App;
```

There is no `React.StrictMode`, here is the `index.js` file

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

// import { RecoilRoot } from 'recoil';
import { RecoilRoot } from 'recoil-next/cjs/recoil';

ReactDOM.render(
  <RecoilRoot>
    <App />
  </RecoilRoot>,
  document.getElementById('root')
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
```

So, still the same; it renders two times 😕

**Comment by suren-atoyan** [comment] 2020-09-10 12:02
But there is a huge improvement regarding further updates

1) we get just one update after each `setValue`
2) we don't get any update if the new value is equivalent to the previous one

So, that's really great 🎉 only remains the initial render issue

**Comment by davidmccabe** [comment] 2020-09-10 17:55
Does the extra render on initial mount happen with the experimental release of React?

**Comment by suren-atoyan** [comment] 2020-09-10 18:02
> Does the extra render on initial mount happen with the experimental release of React?

no,

react - v16.13.1
react-dom - v16.13.1

**Comment by davidmccabe** [comment] 2020-09-10 18:05
Ah, an extra render on mount is expected when using React 16. It is eliminated when using new experimental React APIs.

**Comment by suren-atoyan** [comment] 2020-09-10 18:09
> Ah, an extra render on mount is expected when using React 16. It is eliminated when using new experimental React APIs.

ah, I see

**Comment by lPaths** [comment] 2020-11-28 04:57
Hi @davidmccabe, May this get fixed in react@17 too instead of experimental version only?

**Comment by jaytarr** [comment] 2020-12-04 20:23
Currently seeing this in React 17.0.1. Is this expected?

**Comment by salvoravida** [comment] 2021-01-05 10:31
Issue CodeSandBox
https://codesandbox.io/s/recoil-legacy-double-render-30bjc

Fix CodeSandBox
https://codesandbox.io/s/recoil-legacy-double-render-fixed-2oxfj

@jaytarr 
you can test the pr with package '@salvoravida/recoil' 0.1.3
