### ISSUE TITLE
selector async source refresh????

### ISSUE THREAD

**Issue by mingiki** [facebookexperimental/Recoil#942] opened 2021-03-25 08:50 UTC
hi

With selector async, the data in the form of a list is fetched from the api.
I want to add data to the list and bring the list back
Is there any way to get the data of the selector back?

I want the process below.
-  1. => 2.=> add event => refresh quizs => 1.

1. list component
`const quizs = useRecoilValue(quizRecoil.getQuizList);
`
2. add component
```
  let res = await api.insertQuiz(param);
    if (res.data.result_code === 200) {
        setIsAddQuiz(false);
       // quizs();?????
    }

```
3. recoil component
```
  export const getQuizList = selector({
      key: 'getQuizList',
      get: async ({ get }) => {
          let param = {
              siteID : "coaching365"
          }
        const res = await api.getQuizList(param);
        return res.data.result_code === 200 ? res.data.result.Quiz : [];
      },
      set: ({ set }, value) => {
          if (value) {
            set(quizsState);
          }
      }  
  });
```

**Comment by 42shadow42** [comment] 2021-03-27 01:07
Are you asking about these patterns? https://recoiljs.org/docs/guides/asynchronous-data-queries#query-refresh

**Comment by mingiki** [comment] 2021-03-31 04:56
thanks

**Comment by drarmstr** [comment] 2021-04-01 01:37
Sounds like a duplicate of #422?

**Closed by drarmstr** 2021-04-01 01:37 UTC
Labels: duplicate
