### ISSUE TITLE
async selector does not update when atom value used after await changes

### ISSUE THREAD

**Issue by el-angel** [facebookexperimental/Recoil#341] opened 2020-06-17 15:29 UTC
[sandbox!](https://codesandbox.io/s/userecoilvalueloadable-not-reloading-kkrk3?file=/src/App.js)

My selector uses an atom, when I update that atom, I assume my selector should update as well since it uses it internally. Am I wrong?

**Comment by Shmew** [comment] 2020-06-17 16:43
You should separate the async query into a separate `selector`/`selectorFamily` and compose the two with a third `selector`, something like this:

```js
const asyncPromise = () =>
  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve();
    }, 5000);
  });

const atom1 = atom({
  key: "atom1",
  default: 1
});

const selectorTest = selector({
  key: "selectorTest",
  get: async ({ get }) => {
    return await asyncPromise();
  }
});

const selector1 = selector({
  key: "selector1",
  get: ({ get }) => {
    const a = get(selectorTest);
    const valy = get(atom1);
    console.log({ valy });
    return valy;
  }
});
```

**Comment by stephanoparaskeva** [comment] 2020-06-17 17:06
> You should separate the async query into a separate `selector`/`selectorFamily` and compose the two with a third `selector`, something like this:
> 
> ```js
> const asyncPromise = () =>
>   new Promise((resolve, reject) => {
>     setTimeout(() => {
>       resolve();
>     }, 5000);
>   });
> 
> const atom1 = atom({
>   key: "atom1",
>   default: 1
> });
> 
> const selectorTest = selector({
>   key: "selectorTest",
>   get: async ({ get }) => {
>     return await asyncPromise();
>   }
> });
> 
> const selector1 = selector({
>   key: "selector1",
>   get: ({ get }) => {
>     const a = get(selectorTest);
>     const valy = get(atom1);
>     console.log({ valy });
>     return valy;
>   }
> });
> ```

If you use the get selector for Async actions, how do you update the state based on a response. i've asked this before but still don't understand.

get selectors allow you to get. Asynchronously as well.
how do you set? in an asynchronous way?

**Comment by Shmew** [comment] 2020-06-17 17:38
The idea is not to *set*, but to *compose*. If you have something that needs something else you bring them together into a new selector. 

This can potentially get verbose when you have many stages of this which is why I proposed #317. So you could just do something like `atom1.zip(selectorTest).map((a,s) => a)`

**Comment by drarmstr** [comment] 2020-06-17 22:41
Duplicate of #103 

There is a known issue #103 that dependencies after an async callback or await will not be properly recorded.  We have a fix in the works.

**Closed by drarmstr** 2020-06-17 22:41 UTC
Labels: bug, duplicate
