### ISSUE TITLE
 [BUG] Snapshot has already been released. 

### ISSUE THREAD

**Issue by finite2infinite** [facebookexperimental/Recoil#1994] opened 2022-09-02 18:22 UTC
From [#1891](https://github.com/facebookexperimental/Recoil/pull/1891),
this issue is not fixed at all in dev mode (firefox, safari browser).
when debug console is opened or after page refresh, it keeps throwing the error.
Could you possibly add examples of how to use urlSyncEffect properly?
There's so little examples on the official web site and I have no idea what has been done wrong.

**Comment by drarmstr** [comment] 2022-09-16 22:50
Can you provide a reproducer for the error?  Is this related to #1936?

[`urlSyncEffect()`](https://recoiljs.org/docs/recoil-sync/api/urlSyncEffect) is used the same as [`syncEffect()`](https://recoiljs.org/docs/recoil-sync/api/syncEffect) with just the addition of the `history` option.  See [these examples](https://recoiljs.org/docs/recoil-sync/sync-effect)

**Comment by PiR1** [comment] 2022-09-19 09:16
I have the same issue.
I tried to reproduce it in this codesandbox: https://codesandbox.io/s/stupefied-tree-c2xd7t?file=/src/component.js. The error is thrown when you change the array size (for example from 500 to 5000: ![snapshot has already been released](https://user-images.githubusercontent.com/12834310/190984416-298c2787-35b3-4f42-8e4c-9d0d8f1bc6d5.gif))
I tested this code on Chrome and it doesn't throw any error but it does in Firefox (104.0.2 & 105.0b9). I only tested those 2 navigators.
Also, I don't know if it's the same cause as in my full code.

**Comment by willoughby** [comment] 2022-10-19 10:27
@PiR1 try using the 7.6 release as this resolved the issue for us, we was on 7.4.

**Comment by PiR1** [comment] 2022-10-19 11:57
> @PiR1 try using the 7.6 release as this resolved the issue for us, we was on 7.4.

Yes, I'm on the latest version in my code and in the [codesandbox ](https://codesandbox.io/s/stupefied-tree-c2xd7t?file=/src/component.js) but it doesn't resolve the issue.
As I [said](https://github.com/facebookexperimental/Recoil/issues/1936#issuecomment-1249360263) in the issue #1936 (wich has been "resolved" in the version 7.5), the timeout delay added depends of the computer and app performances. So it doesn't fix the issue in all cases.

**Comment by remigailard80** [comment] 2022-11-03 05:17
Guess this error is about cross browsing issue.
I got same issue on safari, but not on Chrome.

**Comment by davidnaas** [comment] 2023-02-28 13:10
I have this issue as well using  `recoil 0.7.6` and `recoil-sync 0.2.0`.

I'm tied to a very specific version of  webkit/safari webview and this issue makes it virtually impossible to use `recoil-sync` at all since the dev tools can not be opened without crashing the app

**Comment by Atrus619** [comment] 2023-03-07 18:55
I'm having this issue on `recoil 0.7.7`, but only when using `react 18.2.0`, if I use `react 17.0.2` the issue does not occur.

For reference, I am encountering this using a custom component in storybook, and it only occurs under specific circumstances

**Comment by d6u** [comment] 2023-08-20 07:25
I see https://github.com/facebookexperimental/Recoil/pull/2243 is already merged. When are we going to release a new version with this fixed?

**Comment by u5r0** [comment] 2023-10-25 19:42
I'm migrating from Create-React-App to Vite. Recoil works fine in CRA, but it crashes with this error in Vite. Since this's not merged yet, I can't tell which is the problem, Recoil or Vite!

**Comment by carolineartz** [comment] 2023-10-26 22:46
Hi, what is the status here? I see there is a PR https://github.com/facebookexperimental/Recoil/pull/2243 (not merged) but no movement in a while...

**Comment by ghost** [comment] 2023-10-27 08:44
I will close off this issue for now. It's been a while and I've mostly relied on chrome to avoid the hassle.
For those who are experiencing the same issue, I'd suggest using the chrome browser especially for handling large set of data which seems to be the case.

**Closed by ghost** 2023-10-27 08:44 UTC
Labels: pending

**Comment by ghost** [comment] 2023-11-02 05:56
how resolve the problem ?

**Comment by chriszrc** [comment] 2024-07-11 15:00
@Jeffy-Praneat I added pnpm patch to the `autoRelease_INTERNAL()` function, making the timeout 100ms rather than 10, and now it works, see this issue - https://github.com/facebookexperimental/Recoil/issues/1936

**Comment by ArthurGuez** [comment] 2024-07-18 09:35
@chriszrc Thanks, it did the trick for my app
