### ISSUE TITLE
React-three-fiber compatibility

### ISSUE THREAD

**Issue by xixixao** [facebookexperimental/Recoil#559] opened 2020-09-07 21:05 UTC
I would like to use React with react-three-fiber to sync state between Three.js Canvas and the rest of the page. Unfortunately this doesn't work atm, Recoil can only be used to sync state **inside** the Canvas.

This works:
```js
<Canvas>
  <RecoilRoot>
    <ComponentUsingRecoilState />
```

This doesn't work
```js
<RecoilRoot>
  <Canvas>
    <ComponentUsingRecoilState />
```

And I need the latter to do something like:
```js
<RecoilRoot>
  <Canvas>
    <ComponentUsingRecoilState />
  </Canvas>
  <AnotherComponentUsingRecoilState />
</RecoilRoot>
```

Codesandbox for exploration (I don't really know how to debug this as I'm not familiar with Recoil internals):

https://codesandbox.io/s/wizardly-bash-ue9uy

**Comment by cometkim** [comment] 2020-09-08 03:49
Related with https://github.com/facebook/react/issues/13332

**Comment by drarmstr** [comment] 2020-09-08 20:14
Duplicate of #140 

Try using the new `useRecoilBridgeAcrossReactRoots()` hook from #516.  This is currently only in master, but we're working on getting that next release out right now.

**Closed by drarmstr** 2020-09-08 20:14 UTC
Labels: duplicate
