### ISSUE TITLE
Re-fetch from an async function

### ISSUE THREAD

**Issue by Codeia** [facebookexperimental/Recoil#570] opened 2020-09-13 22:01 UTC
**The problem:**
When I enter a page and then come back, I see the initial fetching result regardless of any changes. 

--

Hey everyone,

Really amazed by how simple Recoil is, even to a newbie like me.

I created a simple component that displays list of products.
This is my component:
````
import React, { useEffect } from 'react';
import { productsQuery } from '../../recoil/atoms';
import { useRecoilValueLoadable } from 'recoil';
export function Products({ ...props }) {
  const products = useRecoilValueLoadable(productsQuery)
  const renderProducts = () => {
    switch (products.state) {
      case 'hasValue':
        return <>{JSON.stringify(products.contents)}</>
      default:
      case 'loading':
      case 'hasError':
        return <div>Loading...</div>;
    }
  };
  useEffect(() => {
    renderProducts();
  }, []);
  return (
    <div className="Page">
        {renderProducts()}
    </div>
  );
}
````

And this is my simple selector:
```
// Get all products
export const productsQuery = selector({
  key: 'productsQuery',
  get: async ({get}) => {
    const products = await axios.get(`/api/product/list`)
    return products.data;
  }
});
```

It works great, but when I go to different pages in my app, and return to this page, the fetching isn't really happening, it brings me the old product list regardless of new changes.

**Comment by benbatya** [comment] 2020-09-14 19:34
I have two possible solutions:
Maybe use a trigger atom to force the refetch which is incremented in the useEffect.
Or make productsQuery into a selectorFamily with a fresh id to force a re-fetch

**Comment by drarmstr** [comment] 2020-09-14 23:06
Duplicate of #422

**Closed by drarmstr** 2020-09-14 23:06 UTC
Labels: duplicate

**Comment by drarmstr** [comment] 2020-10-28 20:40
Document query refresh pattern in #676
