### ISSUE TITLE
React warnings re multiple state updates when using a selector that depends on another async selector

### ISSUE THREAD

**Issue by nvanexan** [facebookexperimental/Recoil#242] opened 2020-06-02 22:33 UTC
I have an async selector like so...

```
export const userProfile = selector({
  key: "userProfile",
  get: async ({ get }) => {
    const { data } = await http.get(`/api/profile`);
    return data as Profile;
  },
});
```

And then another selector that makes use of that selector, like so...

```
export const userDependents = selector({
  key: "userDependents",
  get: ({ get }) => {
    const dependents = get(userProfile)?.policies[0].dependents;
    return dependents;
  },
});
```

Calling the second selector from a component like this...

```
  const deps = useRecoilValue(userDependents);
```

This works, but the console keeps issuing a warning about updating a component while rendering a different component. 

![image](https://user-images.githubusercontent.com/489832/83576194-2e61d280-a4ff-11ea-87f5-d5efe066cf45.png)

I believe this is an issue with recoil vs my implementation of recoil, so posting it here.

**Comment by jaredpalmer** [comment] 2020-06-02 22:40
I think this is a know bug that they are working in internally at FB.

**Comment by drarmstr** [comment] 2020-06-19 00:16
Duplicate of #12

**Closed by drarmstr** 2020-06-19 00:16 UTC
Labels: duplicate
