### ISSUE TITLE
DevTools

### ISSUE THREAD

**Issue by 72gm** [facebookexperimental/Recoil#1233] opened 2021-09-21 11:40 UTC
Hi,

Can you advise when you are likely to provide a devtools extension?

Thanks

**Comment by csantos42** [comment] 2021-09-22 01:05
hey! I'll be working on this in the next month or so. Duplicate of #194

**Closed by csantos42** 2021-09-22 01:05 UTC

**Comment by creotip** [comment] 2021-12-18 21:54
Check this out:
https://github.com/creotip/recoil-gear
