### ISSUE TITLE
How to turn off duplicate atom key warning

### ISSUE THREAD

**Issue by huntonas** [facebookexperimental/Recoil#670] opened 2020-10-23 15:15 UTC
We are using next.js that has hot module reloading, and continually get the "Duplicate atom key "blah". This is a FATAL ERROR in production" warning. Is there any way to turn this off for dev? Thanks.

**Comment by janus-reith** [comment] 2020-11-09 11:40
With nextjs I'm getting this both during local development and during build of the production bundle,
and I'm not declaring duplicate keys.

Therefore I can probably rule out HMR as the issue here, but still I wonder if there is an actual issue and values are somehow redefined, or if the Error itself is wrong.

I do access atoms on components that are defined in/under `_app.js` and there span multiple pages, I wonder if that is related somehow.

**Comment by janus-reith** [comment] 2020-11-11 23:37
As this issue is about turning off these warnings, and I‘m still unsure wether there is an actual error with my use of recoil, I created a separate issue here: https://github.com/facebookexperimental/Recoil/issues/733

**Comment by drarmstr** [comment] 2020-11-17 20:10
Duplicate of #733

**Closed by drarmstr** 2020-11-17 20:10 UTC
Labels: duplicate

**Comment by Dev-Markox36** [comment] 2021-12-27 17:56
The only thing i found, is to go to the recoil package file (node_modules/recoil) in all recoil.js and recoil.min.js and comment console.warn(message).

**Comment by progrmoiz** [comment] 2023-04-02 22:32
I'm getting the same warning in development, but I just found out that in their 0.7.6 release, you can turn it off by setting `RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED` to `false`. Check out the release blog here https://recoiljs.org/blog/2022/10/11/recoil-0.7.6-release.

**Comment by Zhoucheng133** [comment] 2024-10-17 13:48
For Next.js, you can edit your `_app.tsx` (or before using `RecoilRoot`) like this: 
```ts
import { RecoilEnv, RecoilRoot } from 'recoil';
function MyApp() {
RecoilEnv.RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED = false;
  return (
    <RecoilRoot>
      // ... other code
    </RecoilRoot>
  );
}
```
